### ISSUE TITLE
Docker build 1.4.2 seems broken

### ISSUE THREAD

**Issue by wornet-aer** [jsuto/piler-examples#2]
I've just pulled `sutoj/piler:1.4.2` from docker hub, and ended up with a 404 "Not found" error from nginx.

After a litlebit of debugging I've found out, that the default nginx config within the container is referencing the old php version `/var/run/php/php7.4-fpm.sock`, but within the container there is only the newer php8.1. socket `/var/run/php/php8.1-fpm.sock` available.

Maybe you want to fix the `/etc/piler-nginx.conf.dist` file which comes shipped within the container.

Keep up the great work! 👍 

Cheers,
Andreas

**Comment by jsuto** [comment]
Just updated the php socket path to use 8.1, rebuilt and pushed the image to docker hub.

**Comment by jsuto** [comment]
Anyway, thanks for noticing ;-)
